"""make order delivery assignment unique

Revision ID: 516d14257379
Revises: fb37c2e5099a
Create Date: 2026-09-25 12:08:28.579580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516d14257379'
down_revision: Union[str, Sequence[str], None] = 'fb37c2e5099a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'delivery_assignments', ['order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'delivery_assignments', type_='unique')
    # ### end Alembic commands ###
