"""add delivery address to orders

Revision ID: afbaeccb0959
Revises: 6b54f0321b17
Create Date: 2026-09-07 20:16:37.812632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afbaeccb0959'
down_revision: Union[str, Sequence[str], None] = '6b54f0321b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('delivery_address_line', sa.String(length=255), nullable=False))
    op.add_column('orders', sa.Column('delivery_city', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('delivery_state', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('delivery_postal_code', sa.String(length=20), nullable=False))
    op.add_column('orders', sa.Column('delivery_latitude', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('delivery_longitude', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivery_longitude')
    op.drop_column('orders', 'delivery_latitude')
    op.drop_column('orders', 'delivery_postal_code')
    op.drop_column('orders', 'delivery_state')
    op.drop_column('orders', 'delivery_city')
    op.drop_column('orders', 'delivery_address_line')
    op.drop_table('addresses')
    # ### end Alembic commands ###
